lib/health_web/router.ex
defmodule HealthWeb.Router do
  use HealthWeb, :router
  use Pow.Phoenix.Router

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  @csp "style-src 'self' 'unsafe-inline' 'unsafe-eval'"

  pipeline :browser do
    plug :accepts, ["html"]
    plug :put_secure_browser_headers, %{"content-security-policy" => @csp}
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  # Unprotected routes
  scope "/" do
    pipe_through :browser

    get "/", HealthWeb.PageController, :index
    resources "/contact", HealthWeb.ContactController, only: [:new, :create]
    pow_routes()

    # View sent emails at http://localhost:4000/sent_emails
    if Mix.env() == :dev do
      # If using Phoenix
      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  # Protected routes
  scope "/", HealthWeb do
    pipe_through [:browser, :protected]
    resources "/users", UserController, only: [:index, :edit, :update]
    # must be before resources "/measurements"
    get "/measurements/export", MeasurementController, :export
    resources "/measurements", MeasurementController
    resources "/weights", WeightController, except: [:new, :show]
    get "/weights/export", WeightController, :export
  end

  # Other scopes may use custom stacks.
  # scope "/api", HealthWeb do
  #   pipe_through :api
  # end
end

lib/health_web/views/layout_view.ex
defmodule HealthWeb.LayoutView do
  use HealthWeb, :view
  import Health.Account.Role
end

lib/health_web/templates/layout/_alert.html.eex
<%= if Enum.count(bootstrap_flash(@conn)) > 0 do %>
  <div class="row">
    <div class="col">

      <%= Enum.map(bootstrap_flash(@conn), fn {key, message} -> %>
        <div class="alert alert-dismissible alert-<%= key %> fade show" role="alert">
          <%= message %>
          <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"> &times;</span>
          </button>
        </div>
      <% end) %>

    </div>
  </div>
<% end %>

lib/health_web/templates/layout/_footer.html.eex
<div id="footer" class="container">
  <div class="row">
    <div class="col text-center">
      <ul>
        <li><a href='https://github.com/alanvardy/health'>GitHub</a></li>
      </ul>
    </div>

    <div class="col text-center">
      <p>Copyright &copy; <%= DateTime.utc_now.year %></p>
    </div>

    <div class="col text-center">
      <ul>
        <li>
          <%= link "Contact", to: Routes.contact_path(@conn, :new) %>
        </li>
      </ul>
    </div>
  </div>
</div>

lib/health_web/templates/layout/_navbar.html.eex
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <img alt="Logo" src="<%= Routes.static_path(@conn, "/images/logo.png") %>" class="mb-2">
    HEALTH
  </a>
  <button class="navbar-toggler" data-aria-controls="navContent" data-aria-label="Toggle navigation"
    data-target="#navContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navContent">
    <ul class="navbar-nav mr-auto">
      <%= if assigns[:current_user] do %>
      <%= nav_link(@conn, "Weight", to: Routes.weight_path(@conn, :index)) %>
      <%= nav_link(@conn, "Measurements", to: Routes.measurement_path(@conn, :index)) %>
      <%= if is?(@current_user, :admin) do %>
      <%= nav_link(@conn, "Users", to: Routes.user_path(@conn, :index)) %>
      <% end %>
      <% end %>
      <%= nav_link(@conn, "Contact", to: Routes.contact_path(@conn, :new)) %>
    </ul>
    <ul class="navbar-nav">
      <%= if assigns[:current_user] do %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbar-dropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <span class="user-email"><%= @current_user.name %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
          <%= link "Settings", to: Routes.pow_registration_path(@conn, :edit), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link "Sign Out", to: Routes.pow_session_path(@conn, :delete), method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= nav_link(@conn, "Register", to: Routes.pow_registration_path(@conn, :new)) %>
      </li>
      <li class="nav-item">
        <%= nav_link(@conn, "Sign in", to: Routes.pow_session_path(@conn, :new)) %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

lib/health_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
  <meta name="robots" content="index, follow" />
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <title>Health - A Phoenix app for keeping us above ground a little longer</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
</head>

<body>
  <%= render "_impersonate.html", conn: @conn %>
  <%= render "_staging.html", conn: @conn %>
  <%= render "_navbar.html", conn: @conn, current_user: @current_user %>
  <div id="content-wrap">
    <div class="container bg-white rounded py-4 my-4">
      <%= render "_alert.html", conn: @conn %>
      <div id="main" class="mx-sm-2 mx-lg-5">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>
  </div>
  <div id="footer-wrap">
    <%= render "_footer.html", conn: @conn %>
  </div>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>